# =================================================================================================
# KUBERNETES MANIFEST: Frontend (Nginx)
# =================================================================================================
# WELCOME STUDENTS!
# This deploys the Static Website (HTML/JS/CSS) served by Nginx.
#
# KEY CONCEPTS:
# 1. Environment Configuration:
#    The Frontend runs in the browser, BUT Nginx acts as a "Reverse Proxy".
#    We need to tell Nginx where the Backend APIs are.
#
#    Wait... Nginx is a text config file. How do we put Env Vars into it?
#    We use a trick in the Dockerfile called 'envsubst'. It reads these valid
#    environment variables (AUTH_API_URL) and writes them into nginx.conf at startup.
# =================================================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/PROJECT_ID/task-app-repo/frontend:latest
          imagePullPolicy: Always

          # ENVIRONMENT VARIABLES for Nginx
          env:
            - name: PORT
              value: "80"

            # Service Discovery:
            # We use the Service Names ("auth-api", "tasks-api") as hostnames.
            # Kubernetes DNS resolves "http://auth-api" to the correct internal IP.
            - name: AUTH_API_URL
              value: "http://auth-api:8000/"
            - name: TASKS_API_URL
              value: "http://tasks-api:8000/"

          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: task-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  # Type: ClusterIP (Default)
  # This service is still internal!
  # To expose it to the internet, we use the "Ingress" (see ingress.yml).
  type: ClusterIP
